services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    environment:
      - PUBLIC_HOST=localhost
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - genesys-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8081:80" # Volta para 8081 para funcionar o http://localhost:8081
    restart: unless-stopped
    networks:
      - genesys-network

networks:
  genesys-network:
    driver: bridge
