# Build Stage
FROM gradle:8-jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
# Aumentamos a memória do Gradle e do Kotlin Daemon para evitar OutOfMemory
RUN ./gradlew :composeApp:jsBrowserDistribution --no-daemon \
    -Pandroid.useAndroidX=true \
    -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"

# Runtime Stage (Nginx para servir o JS/HTML)
FROM nginx:stable-alpine
COPY --from=build /home/gradle/src/composeApp/build/dist/js/productionExecutable /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
