# Runtime Stage
FROM eclipse-temurin:21-jre-jammy

# Cria diretórios necessários
RUN mkdir -p /app/bin /app/lib /app/uploads /app/data

# Copia as bibliotecas e o executável
COPY deploy/server/lib /app/lib
COPY deploy/server/bin /app/bin

# Define permissões de execução
RUN chmod +x /app/bin/server

WORKDIR /app/bin

EXPOSE 8080

# Define variáveis de ambiente padrão
ENV PUBLIC_HOST=localhost

# Comando de entrada usando o script gerado pelo Gradle
ENTRYPOINT ["./server"]
