user  nginx;
worker_processes  auto;
events {
    worker_connections  1024;
}
http {
    include       /etc/nginx/mime.types;
    types {
        application/wasm wasm;
    }
    default_type  application/octet-stream;

    server {
        listen       80;
        root   /usr/share/nginx/html;
        index  index.html;

        add_header Access-Control-Allow-Origin * always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval' 'wasm-unsafe-eval' 'unsafe-inline' https://www.gstatic.com; style-src 'self' 'unsafe-inline'; img-src * data: blob:; connect-src 'self' *;" always;

        location / {
            try_files $uri $uri/ /index.html;
            # Passa o host real para o backend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location ~* \.(js|mjs|wasm|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 1h;
            add_header Cache-Control "public, no-transform";
            add_header Access-Control-Allow-Origin * always;
        }

        error_page 404 /index.html;
    }
}
