package com.itbenevides.genesys21.ui.theme

object GenesysStrings {
    // Common
    const val AppName = "Genesys21"
    const val Back = "Voltar"
    const val Save = "Salvar"
    const val Cancel = "Cancelar"
    const val Confirm = "Confirmar"
    const val Delete = "Excluir"
    const val Edit = "Editar"
    const val Publish = "Publicar"
    const val Loading = "Carregando..."
    const val Total = "Total"
    const val SearchPlaceholder = "O que você procura hoje?"
    const val Categories = "Categorias"
    const val All = "Todos"
    const val Preview = "Pré-visualização"
    const val Identification = "Identificação"
    const val Details = "Detalhes"
    const val Description = "Descrição"
    const val PricePrefix = "R$ "
    const val OrderPrefix = "PEDIDO #"
    const val SessionIdPrefix = "ID: "

    // Login
    const val Welcome = "Bem-vindo"
    const val LoginSubtitle = "Faça login para continuar"
    const val EmailLabel = "Email"
    const val PasswordLabel = "Senha"
    const val LoginButton = "Entrar"
    const val Logout = "Sair"

    // Page List & Admin
    const val AdminTitle = "Administração"
    const val ManageVitrines = "Gerenciar Vitrines"
    const val ManageVitrinesSubtitle = "Crie e gerencie seus canais de venda ativos."
    const val NoPagesFound = "Nenhuma página criada"
    const val NoPagesDescription = "Toque no + para criar sua primeira vitrine."
    const val NoOrdersFound = "Nenhum pedido encontrado"
    const val NoOrdersDescription = "Nenhum pedido registrado nesta vitrine."
    const val SearchOrdersLabel = "Buscar pedido ou cliente"
    const val Revenue = "Receita"
    const val Pending = "Pendentes"
    const val VitrineTab = "Vitrine"
    const val OrdersTab = "Pedidos"
    const val GlobalSettings = "Configurações Globais"
    const val CustomDomainLabel = "Domínio Customizado"
    const val WhatsAppLabel = "WhatsApp"

    // Editor (WhiteLabel)
    const val NewPageTitle = "Nova Página"
    const val EditPageTitle = "Configurações da Vitrine"
    const val PageTitleLabel = "Título da Página"
    const val PageTitlePlaceholder = "Ex: Minha Loja Premium"
    const val SavePageButton = "Salvar Alterações"
    const val CreateProfessionalVitrine = "Criar Vitrine Profissional"
    const val CreateEmptyVitrine = "Criar em Branco"
    const val EmptyEditorTitle = "Sua vitrine está vazia"
    const val EmptyEditorDescription = "Adicione blocos de conteúdo para começar a montar sua página."

    const val BlockSettings = "Configurações do Bloco"
    const val BlockSettingsDescription = "Personalize como este conteúdo aparece na sua vitrine."
    const val BlockNameLabel = "Nome do Bloco (Opcional)"
    const val BlockNamePlaceholder = "Ex: Promoções da Semana"
    const val SelectBlockToEdit = "Selecione um bloco"
    const val SelectBlockToEditDesc = "Toque no ícone de lápis para editar."
    const val PhotosLimit = "/5"
    
    const val TitleTextLabel = "Texto do Título"
    const val ContentTextLabel = "Conteúdo do Texto"
    const val Alignment = "Alinhamento"
    const val FontSize = "Tamanho da Fonte"
    const val UppercaseOption = "Tudo Maiúsculo?"
    const val BrandColorOption = "Cor da Marca?"
    const val FontStyle = "Estilo"
    const val UpdateTitle = "Salvar Título"
    const val SaveText = "Salvar Texto"
    const val CustomizeStyle = "Personalizar Estilo"
    const val ThemeDescription = "Selecione a paleta de cores para sua marca."
    const val AddBlockTitle = "Adicionar Bloco"
    const val AddBlockDescription = "Escolha o tipo de conteúdo."
    const val EditorThemes = "Estilos"
    const val AddBlockAction = "Adicionar Bloco"
    const val ButtonDefaultText = "Toque Aqui"

    // Product & Cart
    const val NewProduct = "Novo Produto"
    const val EditProduct = "Editar Detalhes"
    const val ProductName = "Nome do Produto"
    const val ProductPrice = "Preço"
    const val ProductStock = "Estoque"
    const val ProductCategory = "Categoria"
    const val ProductDescription = "Descrição"
    const val PhotosTitle = "Fotos do Produto"
    const val ProductGeneralInfo = "Informações Gerais"
    const val CartTitle = "Seu Carrinho"
    const val EmptyCartTitle = "Carrinho Vazio"
    const val EmptyCartDescription = "Adicione itens para continuar."
    const val CheckoutButton = "Finalizar Pedido"
    const val CustomerNameLabel = "Seu Nome"
    const val CheckoutNameHint = "Como gostaria de ser chamado?"
    const val FillNameReminder = "Preencha seu nome para finalizar"
    const val AddedToCartTitle = "Adicionado!"
    const val AddedToCartMessageSuffix = "foi adicionado ao carrinho."
    const val OutOfStockMessage = "Sem estoque disponível!"
    const val ContinueShopping = "Continuar Comprando"
    const val ViewCart = "Ver Carrinho"
    const val AddToCartAction = "Adicionar ao Carrinho"
    const val ProductDescriptionFallback = "Este é um produto premium disponível na Genesys21."

    // Order History & Tracking
    const val OrderSummary = "Resumo do Pedido"
    const val OrderHistoryTitle = "Meus Pedidos"
    const val TrackOrderTitle = "Acompanhamento"
    const val OrderNotFound = "Pedido não localizado"
    const val OrderStatusLabel = "STATUS ATUAL"
    const val OrderTotal = "Total do Pedido"
    const val WhatsAppContactAction = "WhatsApp"
    const val NoHistoryTitle = "Nenhum pedido"
    const val NoHistoryDescription = "Você ainda não possui pedidos registrados."
    
    const val StatusPending = "Pendentes"
    const val StatusProcessing = "Em curso"
    const val StatusCompleted = "Concluídos"
    const val StatusCancelled = "Cancelados"

    // Component Types
    const val ComponentTypeHeader = "Cabeçalho"
    const val ComponentTypeHeaderText = "Título grande."
    const val ComponentTypeText = "Texto"
    const val ComponentTypeTextDesc = "Conteúdo textual."
    const val ComponentTypeProductList = "Lista de Produtos"
    const val ComponentTypeProductListDesc = "Itens à venda."
    const val ComponentTypeImage = "Imagem"
    const val ComponentTypeImageDesc = "Banner visual."
    const val ComponentTypeButton = "Botão"
    const val ComponentTypeButtonDesc = "Link externo."
    const val ComponentTypeFilter = "Filtro"
    const val ComponentTypeFilterDesc = "Busca ativa."

    // Product List Editor
    const val ManageProducts = "Gerenciar Produtos"
    const val AddNewProduct = "Novo Produto"
    const val TabProductsInList = "Nesta Lista"
    const val TabProductsInCatalog = "Do Catálogo"
    const val AddToThisList = "Adicionar à Lista"
    const val RemoveFromThisList = "Remover da Lista"
    const val NoProductsInCatalog = "Nenhum outro produto no catálogo."
    const val SaveLabel = "Salvar"
    const val HorizontalListLabel = "Lista Horizontal?"
}
