name: CI - Multiplatform Build

on:
  push:
    branches: [ mainn, master ]
  pull_request:
    branches: [ mainn, master ]

jobs:
  build-android-server-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Google Services JSON (Android)
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON_ANDROID }}' > composeApp/google-services.json

      - name: Decode Firebase Admin JSON (Server)
        run: |
          mkdir -p server/src/main/resources
          echo '${{ secrets.FIREBASE_ADMIN_JSON }}' > server/src/main/resources/genesys21-32035-firebase-adminsdk-fbsvc-d57f39d3c3.json

      - name: Build Android
        run: ./gradlew :composeApp:assembleDebug -Pandroid.useAndroidX=true

      - name: Build Server
        run: ./gradlew :server:build -Pandroid.useAndroidX=true

      - name: Build Web (JS)
        run: ./gradlew :composeApp:jsBrowserDistribution -Pandroid.useAndroidX=true

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Google Service Info Plist (iOS)
        run: echo '${{ secrets.GOOGLE_SERVICES_PLIST_IOS }}' > iosApp/iosApp/GoogleService-Info.plist

      - name: Build iOS Framework
        # Usando a task genérica de link para o simulador
        run: ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64 -Pandroid.useAndroidX=true

      - name: Build Xcode Project
        working-directory: iosApp
        run: |
          xcodebuild -project iosApp.xcodeproj \
                     -scheme iosApp \
                     -sdk iphonesimulator \
                     -configuration Debug \
                     build \
                     CODE_SIGNING_ALLOWED=NO
